__version__ = '0.2.6'
__name__ = 'dynalist'
__description__ = 'Unofficial Dynalist API Written in Python'
__url__ = 'https://github.com/georgefeng/dynalist'
__author__ = 'feng'
__authoremail__ = 'edu_feng@163.com'
__license__ = 'The MIT License (MIT)'
__copyright__ = 'Copyright 2018 feng'